[package]
name = "work-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
dirs.workspace = true
tempfile.workspace = true
chrono.workspace = true
include_dir.workspace = true
ureq = { version = "2", default-features = false }
semver = "1"

[dev-dependencies]
toml = "0.8"
